=== bakshi41c/mdt_server/schema/event_schema.json
{
  "definitions": {},
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "http://ucl.ac.uk/gosh/event_schema.json",
  "type": "object",
  "title": "Meeting Event Schema",
  "required": [
    "by",
    "meetingId",
    "_id",
    "timestamp",
    "type"
  ],
  "properties": {
    "by": {
      "$id": "#/properties/by",
      "type": "string",
      "title": "By",
      "description": "Public key of sender"
    },
    "meetingId": {
      "$id": "#/properties/meetingId",
      "type": "string",
      "title": "Meeting Id"
    },
    "_id": {
      "$id": "#/properties/_id",
      "type": "string",
      "title": "Event ID",
      "description": "Signature of the event by the sender"
    },
    "timestamp": {
      "$id": "#/properties/timestamp",
      "type": "number",
      "title": "Timestamp",
      "description": "The Unix Timestamp of the event",
      "default": 0,
      "examples": [
        "1552875911"
      ]
    },
    "type": {
      "$id": "#/properties/type",
      "type": "string",
      "enum": [
        "start",
        "join",
        "leave",
        "poll",
        "pollEnd",
        "vote",
        "comment",
        "reply",
        "discussion",
        "disagreement",
        "patientDataChange",
        "ack",
        "joinAck",
        "pollEndAck",
        "ackError",
        "end"
      ],
      "title": "EventType",
      "description": "The type of event",
      "examples": [
        "start"
      ]
    },
    "room": {
      "$id": "#/properties/room",
      "type": "string",
      "title": "The Room ID"
    },
    "refEvent": {
      "$id": "#/properties/refEvent",
      "type": "string",
      "title": "The Reference Event",
      "description": "All events apart from start must refer a previous event"
    },
    "content": {
      "$id": "#/properties/content",
      "type": "object",
      "title": "The Content"
    }
  }
}

=== bakshi41c/mdt_server/tests/discussion_event.json
{
  "_id": "0x98de92adab7827a03ad6d25edc98934dfae889bab1074b5cfae9e8d095d5e4221583ea5df476d3e0bfa6ed47fc2d6fd927685e9130bb6c6a27da4d06aaaac9a81c",
  "by": "0xa78e5bb6ff6a849e120985d32532e5067f262e19",
  "content": {
    "patient": "3069ab8b-2a44-4993-9fa2-4218dd3f2631"
  },
  "meetingId": "b05674b1-400b-4411-a668-71203331c67a",
  "refEvent": "0xff52779cf0b4848f9b4851131503c4154b76278fed8fb1a41615541df8ca40642670e052226fcdae32d4fbb4dbfa8563b559b4476f82d295d135cdb3546e2b6b1b",
  "timestamp": 1555286311,
  "type": "discussion"
}

=== bakshi41c/mdt_server/tests/reply_event.json
{
  "_id": "0xff3d418ef7d2fc2f5328eff5dabf976623a490a1df504ee011e239314912dc3871fde63b76b8a02dcc5dd39e187102b379405e8eaadf96a66d44ebc2a3d0fc8f1c",
  "by": "0xa78e5bb6ff6a849e120985d32532e5067f262e19",
  "content": {
    "reply": ":O"
  },
  "meetingId": "b05674b1-400b-4411-a668-71203331c67a",
  "refEvent": "0x635574a746cb6a4400dd4d12238acd74e1fc67cec9f206b87ddd4f908eeb85db6741bbf52e34c75870a60771256312811616e4753795953640fdf390df46e83e1c",
  "timestamp": 1555279346,
  "type": "reply"
}

=== bakshi41c/mdt_server/tests/poll_event.json
{
  "_id": "0xb617545aa4286cf093f13d226819780e6996f9a5a931b13b82c033db8c2c83fd48345903ea3fdbac6a1f20b68491fea9f503642370ca25723a0c6d08d7e18de61b",
  "by": "0xa78e5bb6ff6a849e120985d32532e5067f262e19",
  "content": {
    "options": [
      "Yes",
      "No"
    ],
    "patient": "",
    "question": "Vote Check?",
    "votingKey": "0cef88ca458ea9c4b4a2686202bc2b73da6b70c4701b97c217414162e7bf4e067f6e1f07425dd7896055a9e4fbd8349e8dd1bfe252c4e26b9859e39ddb8295af"
  },
  "meetingId": "b05674b1-400b-4411-a668-71203331c67a",
  "refEvent": "0x2b9e2f40d25576f00144eb7f68839a2d70edcd97dfe7d703214d84b30896000323f2bcc67afd2bcfa21da3311205e220d6f028342c27496d812ba51ae370db371b",
  "timestamp": 1555285058,
  "type": "poll"
}

=== bakshi41c/mdt_server/tests/general_event.json
{
  "_id": "0x18f7ba2d216b647eedfd716297ed917a5e04b6dcd425f0e52fc1952963ce78792ee2df35c3e57f4098b92d2650375e4b4d242935a162a8c92716d5d57f5cfe411c",
  "by": "0x1c0b2f7a73ecbf7ce694887020dbcbaaa2e126f7",
  "refEvent": "0x6772b7f32c4bb844ae4bf4edc2fec00f36dad18d3cb00c768a004c602f5bdee830fa4b81bd7c695c378cd35cea3e26fca33d886cf03831ed4f93b8cdebe7c3cd1b",
  "timestamp": 1555296990,
  "meetingId": "a5521b9a-0389-4f9e-938e-6aa168a86fac",
  "type": "ack",
  "content": {}
}

=== bakshi41c/mdt_server/tests/start_event.json
{
  "_id": "0xb9757ff31d16cf469cfeab76e889f83e3dedc10ba6992ec9a65b279d0feba31823d43c30f1f7e33e9a71210173966c93d8092af5f4dde1db73dc334cb919d32b1c",
  "by": "0xa78e5bb6ff6a849e120985d32532e5067f262e19",
  "content": {
    "deeIDLoginSigSigned": {
      "data": "0xB2d77F16EC4080598Eb5B8EEaDB3FfF8754970A0",
      "deeID": "0xa78e5bb6ff6a849e120985d32532e5067f262e19",
      "expirytime": "",
      "msg": "2a7d1a6c-3d2c-45f2-b56f-54f10152289e0xa78e5bb6ff6a849e120985d32532e5067f262e19undefined0xB2d77F16EC4080598Eb5B8EEaDB3FfF8754970A0",
      "signature": "0x89279b3fa48c70574b1185b8a1f69ecd98aa19b8d0691c29fecb94f2e9d071b47a99807cfb625cd4e0b03c351b89a2291b1c1344d420334fd5ae7818a9d17dbe1c",
      "type": "loginSigSigned",
      "uID": "2a7d1a6c-3d2c-45f2-b56f-54f10152289e"
    },
    "key": "0xB2d77F16EC4080598Eb5B8EEaDB3FfF8754970A0",
    "meeting": {
      "_id": "b05674b1-400b-4411-a668-71203331c67a",
      "attendedStaff": [],
      "contractId": "",
      "date": "2019-04-18T10:00:03.000Z",
      "description": "April weekly meeting",
      "ended": false,
      "host": "0xa78e5bb6ff6a849e120985d32532e5067f262e19",
      "patients": [
        "6014c065-b342-4aa0-97de-0a24cf39f9b9",
        "0f5047a0-12d7-41d0-82a4-b08d541413a7",
        "1a0cb848-6877-4453-bfa5-c86589f193ae",
        "3d7a1a66-e9f6-4953-bfc7-73014597cb0d",
        "610d5193-2bb1-41d8-b75e-0bdc7cb193d6",
        "3069ab8b-2a44-4993-9fa2-4218dd3f2631"
      ],
      "staff": [
        "0x3b94C961D6A18374e348094F16A928Af0170Ea0b",
        "0xa78e5bb6ff6a849e120985d32532e5067f262e19",
        "0x06f42Cd1000B815DBAE5a77C589EBfffAC92B900",
        "0xe8a30CBB8650C2D03C3903E7047fca60440fd21A",
        "0xf4638dA379e62C2aF06893155a06D79C2ef13741",
        "0x4098B4a5336d5333E8746AAbA59a933cA3aEAf35",
        "0x76B6Cd8931351d393FBD84460F65C393154d12bB",
        "0xaB250eac05468f2BA9F23B39cf4964ab8dA76278",
        "0x28F31CA2Ae0bc00BD27266A012d999245b26a29d",
        "0x232B227AFd46a854601dcB075ff2F6ED97647D28",
        "0x782460591713Ec2B33B6E947319976d1A210080F",
        "0x359b88Ee6CbA3aE0bDF0CD54Fcd5Ddf22f6d5df5"
      ],
      "started": false,
      "title": "MDT meeting"
    },
    "otp": "8636"
  },
  "meetingId": "b05674b1-400b-4411-a668-71203331c67a",
  "refEvent": "genesis",
  "timestamp": 1555279320,
  "type": "start"
}

=== bakshi41c/mdt_server/tests/join_event.json
{"_id": "0x47f22752326fca1d3ff19caa46d82617fe7299c81764d97917b2c51a0e1729d2638ea5767d5a6c8e24ad076ea761790f4ac59c6092ce2536a16cec8228376aea1b",
  "by": "0xa78e5bb6ff6a849e120985d32532e5067f262e19",
  "content": {
    "deeIDLoginSigSigned": {
      "data": "0xB2d77F16EC4080598Eb5B8EEaDB3FfF8754970A0",
      "deeID": "0xa78e5bb6ff6a849e120985d32532e5067f262e19",
      "expirytime": "",
      "msg": "2a7d1a6c-3d2c-45f2-b56f-54f10152289e0xa78e5bb6ff6a849e120985d32532e5067f262e19undefined0xB2d77F16EC4080598Eb5B8EEaDB3FfF8754970A0",
      "signature": "0x89279b3fa48c70574b1185b8a1f69ecd98aa19b8d0691c29fecb94f2e9d071b47a99807cfb625cd4e0b03c351b89a2291b1c1344d420334fd5ae7818a9d17dbe1c",
      "type": "loginSigSigned",
      "uID": "2a7d1a6c-3d2c-45f2-b56f-54f10152289e"
    },
    "key": "0xB2d77F16EC4080598Eb5B8EEaDB3FfF8754970A0",
    "otp": "8636"
  },
  "meetingId": "b05674b1-400b-4411-a668-71203331c67a",
  "refEvent": "join",
  "timestamp": 1555279322,
  "type": "join"
}

=== bakshi41c/mdt_server/tests/vote_event.json
{
  "_id": "0xd7169b0c864d105f890024a6f8b8ceb4a78319ffb4024f2164e4eb087cb743a06b96d1ade5542400210e5c1058c55466a807c7ec608d7d87b465bbec3a000c031c",
  "by": "0xa78e5bb6ff6a849e120985d32532e5067f262e19",
  "content": {
    "vote": "e0546c112eed8ca1c3e09f8b2b9e97a103e5daf7f560fe8e63c4fb97dc591977fb44dfb2c405c22d8b1b0739bd7ed92e006ce99b74eb3a905b6f8326b5db7b1950dd2d9deba1a457833f691e5b0b37a395f034ed365d78d0824079680020cb37d204c81757e43b96b3190d7ccf41673fbdfbced2a06587a34de3d06d71f74e453d164bb0c7eab640d41d9733ecf30fa8e2a36d823565353e324796679711157e671b9be586f2e931098e3714ea26972eb6b953995b1a1b6c337739147ba425ac2992ff0858664bc82b9e769bab6066744c77402656a97aec42b8062e3a97f37af38be04f983301ccc1a3797c4954e21d022c8b44a714281484712927c2838ff70ec9d4a9b49f8e8a59eb77b30f084f8bb392043c1eb3ccbee04d653bed4ee8b1af"
  },
  "meetingId": "b05674b1-400b-4411-a668-71203331c67a",
  "refEvent": "0xb617545aa4286cf093f13d226819780e6996f9a5a931b13b82c033db8c2c83fd48345903ea3fdbac6a1f20b68491fea9f503642370ca25723a0c6d08d7e18de61b",
  "timestamp": 1555285064,
  "type": "vote"
}

=== bakshi41c/mdt_server/tests/comment_event.json
{
  "_id": "0x635574a746cb6a4400dd4d12238acd74e1fc67cec9f206b87ddd4f908eeb85db6741bbf52e34c75870a60771256312811616e4753795953640fdf390df46e83e1c",
  "by": "0xa78e5bb6ff6a849e120985d32532e5067f262e19",
  "content": {
    "comment": "I will be back",
    "patient": ""
  },
  "meetingId": "b05674b1-400b-4411-a668-71203331c67a",
  "refEvent": "0x269cbdf2bf42f68e9e41629abf3b7e7d58f9788aa7f6fffa8cdad10361ed5ea92204a70b593bcdb1633cffbe4fe64c6a6e0c46e6a0f675de24ce557f5d70ce6b1b",
  "timestamp": 1555279338,
  "type": "comment"
}
